### PR TITLE
Setting up build

### PR DESCRIPTION
**Pull request by giorgiosironi**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
I should provide a coveralls token to the build. Checking if it doesn't conflict with the one from Travis.

**Comment by giorgiosironi** [comment]
I think I can't generate coveralls tokens when logging in as me or elife-alfred-user there. @gnott can you add the existing token at https://github.com/elifesciences/builder-private/blob/master/pillar/elife-libraries.sls#L7-L10 ?

**Comment by gnott** [comment]
Yup, https://github.com/elifesciences/builder-private/pull/61, thanks!

**Comment by giorgiosironi** [comment]
Now build passes. Coveralls will only comment once per commit, it seems, which is what we want.

**Comment by gnott** [comment]
Thanks @giorgiosironi!  I guess in the future we can drop the travis-ci builds if Alfred is faster and everything is running.

**Pull request merged**
